global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'yamata_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app-beta:9090']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter-beta:9187']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter-beta:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor-beta:8080'] 